- name: deploye website
  hosts: all
  become: true
  tasks:
    - name: delete old files
      file:
        path: /var/www/html/
        state: absent
    - name: copy files in webserver
      copy:
        src: '{{ src_path }}'
        dest: /var/www/html/ 